### ISSUE TITLE
make go-run

### ISSUE THREAD

**Issue by skvili** [mattermost/rtcd#105]
Is there no way to write in 2-3 sentences how to run your thing?
make go-run
13:25:30 [ ... ] running locally...
/bin/sh: 1: run: not found
13:25:30 [FAIL]
make: *** [Makefile:284: go-run] Error 1

**Comment by streamer45** [comment]
@skvili Did you give the [Getting started guide](https://github.com/mattermost/rtcd/blob/master/docs/getting_started.md) a try?

If you'd like to run it without `docker` through the `make go-run` command you'll need [Golang](https://go.dev/doc/install) installed.

Otherwise you could just download a binary from https://github.com/mattermost/rtcd/releases/tag/v0.10.1 and execute it normally.

**Comment by streamer45** [comment]
Closing this for now but please let us know if you need further support.
